
export const HOUSEHOLD_CREATE_ERR = 'HOUSEHOLD_CREATE_ERR';
export const HOUSEHOLD_CREATE_START = 'HOUSEHOLD_CREATE_START';
export const HOUSEHOLD_REGISTER = 'HOUSEHOLD_REGISTER';
export const HOUSEHOLD_CREATE_SHOW_FORM = 'HOUSEHOLD_CREATE_SHOW_FORM';
