
export const HOUSEHOLD_CREATE_ERR = 'HOUSEHOLD_CREATE_ERR';
export const HOUSEHOLD_CREATE_START = 'HOUSEHOLD_CREATE_START';
export const HOUSEHOLD_REGISTER = 'HOUSEHOLD_REGISTER';
export const HOUSEHOLD_SHOW_JOIN_FORM = 'HOUSEHOLD_SHOW_JOIN_FORM';
