version: '3.1'

services:
  postgres:  # a friendly name. this is also DNS name inside network
    image: postgres:10
    environment:
      POSTGRES_PASSWORD: pgpass
    volumes: # Optional, same as -v in docker run
      - ./backend/conf/init/postgres:/docker-entrypoint-initdb.d
      - postgres-hnin-data:/var/lib/postgresql/data
    restart: always

  frontend-server:
    image: nginx
    depends_on:
      - api-server
    ports:
      - "80:80"
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
      - ./backend/conf/server/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: always

  api-server:
    image: gradle:4.6-jdk8
    depends_on:
      - postgres
    command: gradle bootRun
    volumes:
      - gradle-data:/home/gradle/.gradle
      - ./backend:/home/gradle
volumes:
  postgres-hnin-data:
  gradle-data:
