export const MEAL_ADVANCE_DAY = 'MEAL_ADVANCE_DAY';
export const SHOW_LOOKBACK_DAY = 'SHOW_LOOKBACK_DAY';
export const HIDE_LOOKBACK_DAY = 'HIDE_LOOKBACK_DAY';
export const MEAL_FETCH_IN_PROG = 'MEAL_FETCH_IN_PROG';
export const MEALS_FETCHED = 'MEALS_FETCHED';
export const MEAL_FETCH_ERR = 'MEAL_FETCH_ERR';
