export const MEAL_ADVANCE_DAY = 'MEAL_ADVANCE_DAY';

// export const MEAL_CREATE_ERR = 'HOUSEHOLD_CREATE_ERR';
// export const HOUSEHOLD_CREATE_START = 'HOUSEHOLD_CREATE_START';
// export const HOUSEHOLD_REGISTER = 'HOUSEHOLD_REGISTER';
// export const HOUSEHOLD_SHOW_JOIN_FORM = 'HOUSEHOLD_SHOW_JOIN_FORM';
// export const HOUSEHOLD_SHOW_CREATE_FORM = 'HOUSEHOLD_SHOW_CREATE_FORM';
// export const HOUSEHOLD_RETRIEVE_START = 'HOUSEHOLD_RETRIEVE_START';
// export const HOUSEHOLD_RETRIEVE_ERR = 'HOUSEHOLD_RETRIEVE_ERR';