
export const REGISTER_USER = 'REGISTER_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const LOGIN_ERR = 'LOGIN_ERR';
export const LOGIN_DONE = 'LOGIN_DONE';
export const LOGIN_IN_PROG = 'LOGIN_IN_PROG';
export const REGISTER_START = 'REGISTER_START';
export const REGISTER_DONE = 'REGISTER_DONE';
export const REGISTER_ERR = 'REGISTER_ERR';
export const SHOW_USER_SIGNUP_FORM = 'SHOW_USER_SIGNUP_FORM';
export const SHOW_USER_LOGIN_FORM = 'SHOW_USER_LOGIN_FORM';
